### ISSUE TITLE
Cost of this module

### ISSUE THREAD

**Issue by JackEllis** [silinternational/certmagic-storage-dynamodb#18]
Hey there,

We've been using this module at scale for a while now but I've become concerned with costs. I think we're currently spending between $500-1000 each month for the scans. Each day, RCUs ramp up to something like 25,000 on the table. We don't have tens of thousands of rows, so I'm not 100% sure what the issue may be. In my head, I'd never expect it to ramp up to 25,000 RCUs.

Any ideas?

Cheers,

Jack

**Comment by jasonmccallister** [comment]
@JackEllis I'm not entirely sure if this is the issue, but scans on dynamodb tables are usually expensive and the code performs a scan here: https://github.com/silinternational/certmagic-storage-dynamodb/blob/master/storage.go#L180. 

It might make more sense to perform a query over scan there.

**Comment by fillup** [comment]
@JackEllis that is pretty wild, you must be dealing with a LOT of certs! 

Looking into @jasonmccallister's suggestion it may be possible to change to a query instead of scan, but I think it'll also require changing the table schema a bit. In order to do that though I'd need a lot more information about the possible values for keys and values that go into storage. In order to support the `List` method of the [storage interface](https://pkg.go.dev/github.com/caddyserver/certmagic#Storage) we need to be able to search by a prefix. `query` operations require knowing the "partition key" specifically, and then we can filter based on the "sort key". So it may be possible to parse the `key` value being sent to the `Store` and `Load` methods into a separate, but consistent, partition key and sort key, but like I said I'd need to see all the possible values that could go into it to see how that might work.

@mholt do you have any documentation or could you direct me to where I could discover what all the possible keys that go into storage would be? Or at least the general formatting of them to see if there is a clear or natural place that'd make sense to split a partition key and sort key from? Related, under what condition is the `List` method used? And what sort of prefixes are sent to it?

**Comment by mholt** [comment]
@fillup Unfortunately, I'm not sure if there are "natural" split positions for keys. The interface is designed as a generic key-value wrapper that abstracts the file system (package io/fs wasn't a thing yet).

In the purest sense of the abstraction, it's not really feasible (economically) if the backend doesn't allow querying based on prefixes of some sort, like a file system or a SQL `LIKE` query. That does seem like a pretty severe limitation of the backing storage system.

But I wonder if this should be manageable for 99% of CertMagic use cases, especially to help with @JackEllis 's situation.

You can see where CertMagic uses `List()` here: https://sourcegraph.com/github.com/caddyserver/certmagic/-/blob/storage.go#L66:2&tab=references

Here are the main uses, summarized:

- Accounts (to find an email address, for example)
```
accountList, err := am.config.Storage.List(am.storageKeyUsersPrefix(am.CA), false)
```

- OCSP staples (to delete stale responses)
```
ocspKeys, err := storage.List(prefixOCSP, false)
```

- Issuers, sites for each issuer, and assets for each site (to delete expired certificates and keep storage clean)
```
issuerKeys, err := storage.List(prefixCerts, false)
siteKeys, err := storage.List(issuerKey, false)
siteAssets, err := storage.List(siteKey, false) // x2
```

**Comment by jasonmccallister** [comment]
@fillup you might be able to keep the table structure, but use composite keys (e.g. `prefix#key`). It is explained a little better in this post: https://aws.amazon.com/blogs/database/choosing-the-right-dynamodb-partition-key/

This would allow you to use queries on complex keys instead of using scan. You might not need a secondary key when using composite keys.

**Comment by JackEllis** [comment]
We're now working on dropping this from our application and moving to Redis/filesystem. Costs are at $2,000+ each month now, which is crazy. Thanks so much for all the effort you put into this module, @fillup, and I'm so sorry I can't contribute more here.

**Comment by alexdebrie** [comment]
I took a look through this and have a few suggestions. I tried to categorize them based on level of work, in this module and in `certmagic` or `caddy` generally.

* **(Easy) Stop using [consistent reads](https://github.com/silinternational/certmagic-storage-dynamodb/blob/425c047ecb157233a3ece8ee6c54bde65f7b8cff/storage.go#L191) for the `List()` functionality.** This would cut the RCU consumption in half for all but the smallest `List()` invocations. Because most of the `List()` usage is for periodic cleanup, having an eventually consistent read shouldn't affect functionality much.

* **(Medium) Make [`storageCleanInterval`](https://github.com/caddyserver/caddy/blob/ec309c6d52fdfce0431a1303a49f28c3f546176a/modules/caddytls/tls.go#L510) configurable.** Currently, the [`CleanStorage` method runs every 12 hours](https://github.com/caddyserver/caddy/blob/ec309c6d52fdfce0431a1303a49f28c3f546176a/modules/caddytls/tls.go#L413-L466), and this calls `deleteExpiredCerts` (discussed below), which appears to be the source of the high read traffic. If this could be extended or disabled, users could handle their own expiration rather than running this every 12 hours.

* **(Hard) Fix `deleteExpiredCerts` for non-hierarchical data stores.** The [`deleteExpiredCerts`](https://github.com/caddyserver/certmagic/blob/e4f02628f495eb24bce454aac130e29cd7fb4c15/maintain.go#L488) method uses the `List()` call in four places. Additionally, the second call of `List()` is within a loop based on matches from the first call, and the third and fourth calls are within sub-loops based on the matches from the second call.

    This approach may work well for hierarchical data stores that allow efficient prefix-based search, but it results in a lot of full-table scans with DynamoDB. From what I could understand, this results in 1 + 3N `List()` calls to the DynamoDB module, where N is the number of certificates in your table. Note that these `List()` calls are *full-table scans*, so 1000 certificates in your table would result in 3001 full-table scans.
    
    One way to handle this would be to extend the `Storage` class by adding an optional `FetchCertificates` method or something similar. For modules that implement it (this on!), it could use a more efficient way to fetch all the certificates. For other modules, it could use the default, hierarchical approach.
    
    It'd also be great if it didn't have to [read the item after performing the `List()`](https://github.com/caddyserver/certmagic/blob/e4f02628f495eb24bce454aac130e29cd7fb4c15/maintain.go#L521), as this doubles the read cost by reading the item a second time after a scan. That's a larger change so it's probably fine to just fetch it after the `List()`.

* **(Hard) Rely on DynamoDB TTL to expire.** DynamoDB has a [TTL feature](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html) that automatically expires items after a given timestamp. If we used this to expire certificates and staples, we couldn't need to do the scheduled maintenance job.

    I rated this as 'Hard' as it could require changes to Caddy itself. Right now, the keys and values are treated pretty opaquely when sent to a Storage backend. Now, the DynamoDB module would either need to parse this opaque value to determine an expiry, or Caddy would need to change the call signature for `Store()` to include an expiry. 

The composite key structure + use of Query is a good one too, but it might be tricky to implement in this data model, given @mholt's notes.

Happy to chat / discuss further if needed!

**Comment by mholt** [comment]
> (Medium) Make storageCleanInterval configurable. Currently, the CleanStorage method runs every 12 hours, and this calls deleteExpiredCerts (discussed below), which appears to be the source of the high read traffic. If this could be extended or disabled, users could handle their own expiration rather than running this every 12 hours.

This is something we can do. Storage cleaning is not super critical most of the time, so it doesn't _need_ to happen that often; it's just that it's fine for most users. I'll see what I can come up with.

**Comment by mholt** [comment]
@JackEllis @jasonmccallister @fillup I've committed a configurable storage clean interval to Caddy just now. It seems to work well in my testing: https://github.com/caddyserver/caddy/commit/42b7134ffa3bf3e9e86514c82407979c2627a5ab

I reduced the default scan interval to 24 hours. It can further be configured (with JSON) to run at a different interval, say, `30d`. Would you give it a try Jack? Let me know if you need help using the JSON config for these tests.

**Comment by fgilio** [comment]
Hi @mholt! Is there a way to configure this using Caddyfile? I'm running 2.4.2

**Comment by mholt** [comment]
@fgilio Yes, using the global option: https://caddyserver.com/docs/caddyfile/options#storage-clean-interval

> EDIT: Suppose I have 100 servers syncing on one DynamoDB table, will it be run by all of them or just one?

The servers will all coordinate using your storage backend, DynamoDB in your case; and they will share the resulting certificates, OCSP staples, etc.

**Comment by fgilio** [comment]
Thanks! I'll try it and see how this graph evolves
![Screen Shot 2021-07-26 at 23 18 17](https://user-images.githubusercontent.com/6857732/127084659-f8093343-a228-4745-bc81-b536d091bbde.png)

**Comment by JackEllis** [comment]
@fgilio Matt introduced something to move away from this. Here's our Caddyfile now:

```
{
    on_demand_tls {
        ask https://url-to-check-if-allowed.com
    }

    storage dynamodb caddy_ssl_certificates
    storage_clean_interval 32d
}
```

We now only get a spike once a month.

![image](https://user-images.githubusercontent.com/537943/127085782-021ab9ff-5c6a-4a6a-913f-140d31937b79.png)

**Comment by fgilio** [comment]
Thanks Jack!
